DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID LONG AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(60) NOT NULL, NOMBRE VARCHAR(60) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);
--Insertando Odontologos para Tests --
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('odont-001', 'Nick', 'Riviera'),('odont-002','Gregory',
'House'),('odont-003','Julius','Hibbert'),('odont-004','John','Zoidberg'),('odont-005','Fulano','Mengueche'),
('odont-006','Aquiles','Mata');

DROP TABLE IF EXISTS DOMICILIOS; CREATE TABLE DOMICILIOS (ID LONG AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(50)
NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID LONG AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DNI INT NOT NULL, FECHA DATE NOT NULL, DOMICILIO_ID LONG);

-- para test --
INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Av Siempre Viva', 742, 'Springfield', 'Massachusetts'), ('Calle Wallaby', 42, 'Sydney', 'Nueva Gales del Sur');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Juan', 'Perez', 35464856, '2023-05-24', 1), ('Juana', 'Lopez', 3548546, '2023-05-24', 2);